apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: python-backend
          image: python:3.8-slim
          command: ["python", "-m", "http.server", "8080"]
          ports:
            - containerPort: 8080
